// data/medicineData.js
export const categories = [
  { id: 'all', name: 'All Medicines', icon: '💊' },
  { id: 'pain', name: 'Pain Relief', icon: '🩹' },
  { id: 'fever', name: 'Fever & Cold', icon: '🤒' },
  { id: 'allergy', name: 'Allergy', icon: '🌡️' },
  { id: 'vitamins', name: 'Vitamins', icon: '💪' },
  { id: 'skincare', name: 'Skin Care', icon: '✨' },
  { id: 'diabetes', name: 'Diabetes', icon: '🩺' },
  { id: 'cardiac', name: 'Cardiac Care', icon: '❤️' },
];

export const medicineData = [
  {
    id: 1,
    name: 'Paracetamol 500mg',
    description: 'Effective pain reliever and fever reducer',
    price: 25.99,
    originalPrice: 35.99,
    discount: 28,
    image: '/api/placeholder/300/200',
    category: 'pain',
    manufacturer: 'MediCare Pharma',
    prescriptionRequired: false,
    rating: 4.5,
    reviews: 1247,
    inStock: true
  },
  {
    id: 2,
    name: 'Vitamin C 1000mg',
    description: 'Immune system support and antioxidant protection',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    image: '/api/placeholder/300/200',
    category: 'vitamins',
    manufacturer: 'HealthPlus',
    prescriptionRequired: false,
    rating: 4.7,
    reviews: 892,
    inStock: true
  },
  {
    id: 3,
    name: 'Cetirizine 10mg',
    description: 'Fast-acting allergy relief for seasonal allergies',
    price: 45.50,
    image: '/api/placeholder/300/200',
    category: 'allergy',
    manufacturer: 'AllerFree Labs',
    prescriptionRequired: false,
    rating: 4.3,
    reviews: 567,
    inStock: true
  },
  {
    id: 4,
    name: 'Metformin 500mg',
    description: 'Diabetes management medication',
    price: 89.99,
    image: '/api/placeholder/300/200',
    category: 'diabetes',
    manufacturer: 'Diabeto Care',
    prescriptionRequired: true,
    rating: 4.6,
    reviews: 234,
    inStock: true
  },
  {
    id: 5,
    name: 'Aspirin 75mg',
    description: 'Cardiac care and blood thinner',
    price: 65.25,
    image: '/api/placeholder/300/200',
    category: 'cardiac',
    manufacturer: 'HeartSafe Pharma',
    prescriptionRequired: true,
    rating: 4.4,
    reviews: 178,
    inStock: true
  },
  {
    id: 6,
    name: 'Ibuprofen 400mg',
    description: 'Anti-inflammatory pain relief',
    price: 32.75,
    originalPrice: 45.00,
    discount: 27,
    image: '/api/placeholder/300/200',
    category: 'pain',
    manufacturer: 'PainRelief Inc',
    prescriptionRequired: false,
    rating: 4.2,
    reviews: 945,
    inStock: true
  },
  {
    id: 7,
    name: 'Vitamin D3 2000IU',
    description: 'Bone health and immune support',
    price: 199.99,
    image: '/api/placeholder/300/200',
    category: 'vitamins',
    manufacturer: 'Sunshine Health',
    prescriptionRequired: false,
    rating: 4.8,
    reviews: 678,
    inStock: true
  },
  {
    id: 8,
    name: 'Salicylic Acid Cream',
    description: 'Acne treatment and skin exfoliation',
    price: 156.99,
    image: '/api/placeholder/300/200',
    category: 'skincare',
    manufacturer: 'SkinCare Pro',
    prescriptionRequired: false,
    rating: 4.1,
    reviews: 432,
    inStock: true
  }
];